apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: tchelovilar/guestbook:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        env:
        - name: REDIS_SERVER
          value: "redis"
        ports:
        - containerPort: 80
